### ISSUE TITLE
Provide more precise information on required ID3v2 tags

### ISSUE THREAD

**Issue by madmas** [canoo/canoo-radio#10]
From [MusicController.java](https://github.com/canoo/canoo-radio/blob/3fb67f74c448f14fba61ba11ebc70d8bc7fe3304/canooradio-server/src/main/java/com/canoo/radio/server/controller/MusicController.java) you can see that it is not sufficient to have ID3 information in the mp3 uploaded (as stated in the UI), more specifically, it needs to have the *Artists*, *Album* and *Title* attributes with valid information.
This should also be stated in a error message shown to the user if a upload fails because of missing  tags.

**Comment by victorparmar** [comment]
Done in the new api
