### ISSUE TITLE
allow to browse / sort the entire song database

### ISSUE THREAD

**Issue by canoo-it** [canoo/canoo-radio#13]
in order to sneak around, what all is available on the server without having to guess and try it would be nice, if you could sort by album or sort by artist and browse the entire database

**Comment by madmas** [comment]
@canoo-it, please consider to use a real account for issues and discussions, not a technical one ;-)

**Comment by martin-huber** [comment]
sorry, have been logged in like that from yesterday. It's me.

**Comment by martin-huber** [comment]
ah, yes, and sort by "date uploaded" would be cool

**Comment by madmas** [comment]
and it could try to get the artwork also from the id3 tags (some files have it embedded) to support browsing

**Comment by hkeibel** [comment]
I guess, what we need here is to extend the current Music Browser to a paginated list of all songs, sortable by each column (artist, song, album, albumCover, dateAdded, voteStatus, playCount).

But keep the search/filter function.

**Comment by victorparmar** [comment]
This is a project in itself but yes, would be cool to have :)

**Comment by victorparmar** [comment]
This is now implemented via the ui grid!

**Comment by hkeibel** [comment]
Yay, that's so cool!
