### ISSUE TITLE
Duplication check

### ISSUE THREAD

**Issue by madmas** [canoo/canoo-radio#9]
Detect if a song is already in the radio collection and prevent duplicate uploads.

**Comment by hkeibel** [comment]
For me, as a first quick implementation, it would suffice to detect obvious duplicates solely based on filename and mp3 metadata.

Uploading the exact same file twice happens easily...

**Comment by victorparmar** [comment]
Duplicate file detection is now implemented in the new api (it just overrides the old song). Votes etc. are still preserved
